### ISSUE TITLE
error

### ISSUE THREAD

**Issue by witchfindertr** [KonradIT/bereal-timelapse#1]
Could find no file with path 'output/render_%d.jpg' and index in the range 0-4
output/render_%d.jpg: No such file or directory

images not download

**Comment by Tomy2e** [comment]
I also had this issue, if you're on Windows you need to patch the `cmd/render.go` file

https://github.com/KonradIT/bereal-timelapse/blob/156bcef140c9c1ef4dd1f8a43a1eac6ca363eb18/cmd/render.go#L61

Add the following line after L61:

```go
code = strings.Replace(code, "\r", "", -1)
```

**Comment by KonradIT** [comment]
Fixed in 45ad8e3c69b45bef1ba8a7d9ad0cb7c45eee460d thanks to @Tomy2e

**Comment by witchfindertr** [comment]
now working perfect
