### ISSUE TITLE
Silly query

### ISSUE THREAD

**Issue by iarlaithc** [KonradIT/bereal-timelapse#2]
Hey sorry about this question but i cant figure out how to run this, I have all the requirements but I dont understand how to run the render command. I have ran main.go and it mentioned the usage but typing that command in the same directory in cmd just returns error that bereal-timelapse isnt a recognised command. Id love if you could help at all?
![image](https://user-images.githubusercontent.com/57463324/218505829-be142b29-d8fb-42f6-bcf0-2636a53c48ca.png)

**Comment by KonradIT** [comment]
You need to build it first (`go build -o bereal-timelapse .`) or replace `bereal-timelapse` with `go run main.go`.

**Comment by iarlaithc** [comment]
Thank you
